### ISSUE TITLE
jupyter on k8s

### ISSUE THREAD

**Issue by jiangliuyang1999** [motionlife/k8s-jhub#1]
how can i modify my login.html in a helm application on k8s?

**Comment by motionlife** [comment]
you should mount a init dir for your customized templates. add this in your value.yaml
```
 initContainers:
    - name: git-clone-templates
      image: alpine/git:v2.26.2
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/motionlife/k8s-jhub.git
        - /etc/jupyterhub/custom
      securityContext:
        runAsUser: 1000
      volumeMounts:
        - name: empty-dir-vol
          mountPath: /etc/jupyterhub/custom
  extraVolumes:
    - name: empty-dir-vol
      emptyDir: {}
  extraVolumeMounts:
    - name: empty-dir-vol
      mountPath: /etc/jupyterhub/custom
  extraConfig:
    templates: |
      c.JupyterHub.template_paths = ['/etc/jupyterhub/custom/templates']
  extraConfigMap: {}
```
